### ISSUE TITLE
lack of "Driver_USART.h

### ISSUE THREAD

**Issue by qiujianqin** [MBronsom/OfflineSWD#1]
..\HARDWARE\DAP\SWO.c(26): error:  #5: cannot open source input file "Driver_USART.h": No such file or directory

**Comment by MBronsom** [comment]
请包含ARM CMSIS包中的以下目录
Packs\ARM\CMSIS\5.6.0\CMSIS\Driver\Include
Packs\ARM\CMSIS\5.6.0\CMSIS\Include

**Comment by qiujianqin** [comment]
按照提示操作已经解决。编译无error

**Comment by MBronsom** [comment]
还有其他问题欢迎提出
