### ISSUE TITLE
第一次烧写正常，目标断电后不能再烧写

### ISSUE THREAD

**Issue by ssyqwer** [MBronsom/OfflineSWD#6]
第一次烧写正常，目标断电后不能再烧写，程序卡住
    if(0 == swd_flash_syscall_exec(&flash_algo.sys_call_s, flash_algo.init, flash_start, 0, 0, 0))
        {
            return ERROR_INIT;
        }
        
        
uint8_t swd_flash_syscall_exec(const program_syscall_t *sysCallParam, uint32_t entry, uint32_t arg1, uint32_t arg2, uint32_t arg3, uint32_t arg4)
{
    DEBUG_STATE state = {{0}, 0};
    // Call flash algorithm function on target and wait for result.
    state.r[0]     = arg1;                   // R0: Argument 1
    state.r[1]     = arg2;                   // R1: Argument 2
    state.r[2]     = arg3;                   // R2: Argument 3
    state.r[3]     = arg4;                   // R3: Argument 4
    state.r[9]     = sysCallParam->static_base;    // SB: Static Base
    state.r[13]    = sysCallParam->stack_pointer;  // SP: Stack Pointer
    state.r[14]    = sysCallParam->breakpoint;     // LR: Exit Point
    state.r[15]    = entry;                        // PC: Entry Point
    state.xpsr     = 0x01000000;          // xPSR: T = 1, ISR = 0

    if (!swd_write_debug_state(&state)) {
        return 0;
    }

    if (!swd_wait_until_halted()) {
        return 0;
    }

    if (!swd_read_core_register(0, &state.r[0])) {
        return 0;
    }

    // Flash functions return 0 if successful.
    if (state.r[0] != 0) {
        return 0;
    }

    return 1;
}

static uint8_t swd_wait_until_halted(void)
{
    // Wait for target to stop
    uint32_t val, i, timeout = MAX_TIMEOUT;

    for (i = 0; i < timeout; i++) {
					
        if (!swd_read_word(DBG_HCSR, &val)) {
            return 0;
        }				
        if (val & S_HALT) {
            return 1;
        }
    }

    return 0;
}
卡在最后一个函数，请问怎么解决

**Comment by MBronsom** [comment]
不好意思回复晚了，有点没理解，你的意思是——第一次烧写后，后续都无法继续进行烧写了？还是其他的意思？

**Comment by ssyqwer** [comment]
不好意思，这里是我的flash被保护问题，已经解决，感谢感谢

**Comment by MBronsom** [comment]
好的👌
